kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
        group: educ-k6
      name: ${NAME}
  - apiVersion: v1
    kind: BuildConfig
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:${OUTPUT_TAG}'
      postCommit: {}
      resources: {}
      source:
        contextDir: testing/k6
        git:
          ref: ${SOURCE_REPO_REF}
          uri: ${SOURCE_REPO_URL}
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: openshift/k6/Dockerfile
        type: Docker
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
        group: educ-k6
        component: ${NAME}-buildconfig
      name: ${NAME}
parameters:
  - name: NAME
    value: educ-k6
  - name: OUTPUT_TAG
    value: latest
  - name: SOURCE_REPO_REF
    value: master
  - name: SOURCE_REPO_URL
    value: 'https://github.com/bcgov/educ-keycloak-soam'
