kind: Template
apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/imported-from: 'loadimpact/k6:latest'
          from:
            kind: DockerImage
            name: 'loadimpact/k6:latest'
          generation: null
          importPolicy: {}
          name: latest
          referencePolicy:
            type: ''
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
        group: educ-k6
        component: ${NAME}-imagestream
      name: k6
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
        group: educ-k6
        component: ${NAME}-imagestream
      name: ${NAME}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:${OUTPUT_TAG}'
      postCommit: {}
      resources: {}
      source:
        contextDir: testing/k6/openshift/k6
        git:
          ref: ${GIT_REF}
          uri: ${GIT_REPO}
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'k6:latest'
        type: Docker
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
        group: educ-k6
        component: ${NAME}-buildconfig
      name: ${NAME}
parameters:
  - name: NAME
    value: educ-k6
  - name: OUTPUT_TAG
    value: latest
  - name: GIT_REF
    value: master
  - name: GIT_REPO
    value: 'https://github.com/bcgov/educ-keycloak-soam'
