pipeline {
    agent none
    options {
        disableResume()
    }
    stages {
        stage('SOAM Setup'){
            agent any
            steps{
                script{
                    dir('setup'){
                        echo 'Starting BC Dev Exchange Keycloak Setup...'
                        env.TARGET_ENV = input message: 'User input required', ok: 'Release!',
                            parameters: [choice(name: 'TARGET_ENV', choices: 'dev\ntest\nprod', description: 'Choose the target env for setup')]
                        sh "echo ENV_VALUE=${env.TARGET_ENV} > ./setup/setup-jenkins.properties"
                        sh(
                            returnStdout: true,
                            script: 'bash ./devexchange-keycloak-setup.sh'
                        )
                        echo 'Starting SOAM Setup...'
                        sh 'bash ./soam-keycloak-setup.sh'
                    }
                }
            }
        }
        stage('Update Config Maps'){
            agent any
            steps{
                script{
                    dir('setup'){
                        echo 'Updating config maps... '
                        sh 'bash ./update-configmaps.sh'
                    }
                }
            }

        }
    }
}