---
apiVersion: v1
kind: Template
labels:
  template: setup-pipeline-template'
metadata:
  name: 'setup-pipeline-template'
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: setup-pipeline
    name: setup-pipeline
    namespace: c2mvws-tools
  spec:
    source:
      git:
        ref: master
        uri: 'https://github.com/bcgov/EDUC-KEYCLOAK-SOAM'
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfile: |
          pipeline {
          agent none
          options {
              disableResume()
          }
          stages {
              stage('SOAM Setup'){
                  agent any
                  steps{
                      script{
                          dir('setup'){
                              echo 'Starting BC Dev Exchange Keycloak Setup...'
                              sh './devexchange-keycloak-setup.sh'
                              echo 'Starting SOAM Setup...'
                              sh './soam-keycloak-setup.sh'
                          }
                      }
                  }
              }
              stage('Update Config Maps'){
                  agent any
                  steps{
                      script{
                          dir('setup'){
                              echo 'Updating config maps... '
                              sh './update-configmaps.sh'
                          }
                      }
                  }

              }
            }
          }
    type: JenkinsPipeline