---
apiVersion: v1
kind: Template
labels:
  template: setup-pipeline-template'
metadata:
  name: 'setup-pipeline-template'
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: setup-pipeline
    name: setup-pipeline
    namespace: c2mvws-tools
  spec:
    source:
      git:
        ref: master
        uri: 'https://github.com/bcgov/EDUC-KEYCLOAK-SOAM'
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: "setup/Jenkinsfile"
    type: JenkinsPipeline