pipeline{
   agent {
       label 'maven35'
    }
    stages{
      stage('Build App') {
         steps {
            sh "mvn -f ./api/pom.xml -Dmaven.test.skip=true package"
         }
      }
    }
}